### ISSUE TITLE
ignore bots error

### ISSUE THREAD

**Issue by tec-wizard** [RPGTheGreat/anti-spam#1]
throw err <ignoreBots> option is not set up right!

**Comment by RPGTheGreat** [comment]
Just do ignoreBots : true //to ignore bots or false for not ignore

**Comment by tec-wizard** [comment]
![rpg](https://user-images.githubusercontent.com/64216681/93729554-a7865200-fbe2-11ea-8773-a5e5c346d4cf.PNG)
if i do this, error in console says ignorebots property specified incorrectly
Error says - 
![rpg 2](https://user-images.githubusercontent.com/64216681/93729597-ddc3d180-fbe2-11ea-8018-bb7b76ad158b.PNG)

**Comment by RPGTheGreat** [comment]
oh that's an issue i have to fix it

**Comment by RPGTheGreat** [comment]
Fixed
